### ISSUE TITLE
Incompatible with Kirbre's `onefinity.cps` post processor?

### ISSUE THREAD

**Issue by U007D** [TimPaterson/Fusion360-Batch-Post#47] opened 2022-10-09 13:54 UTC
Pretty new to CNC, but running `Process All` against Kirbre's Onefinity post-processor failed as per attachments.

The Onefinity post-processor can be found [here](https://cam.autodesk.com/hsmposts?p=onefinity).  This is the only Onefinity post-processor available, AFAIAA.

Is there something else I can try?

![Screen Shot 2022-10-09 at 6 53 54 AM](https://user-images.githubusercontent.com/2874989/194760770-8d189737-b03c-4e28-ac14-fa61b0bd26d0.png)
![Screen Shot 2022-10-09 at 6 53 48 AM](https://user-images.githubusercontent.com/2874989/194760774-f82a75c1-3d72-4b59-8ab2-47fe5fd9b53d.png)

**Comment by TimPaterson** [comment] 2022-10-09 16:29
This is a duplicate of Issue #17, although you'd never know by the title (but you would find it by searching Issues for "onefinity"). For convenience, I've pasted in the solution given there with updated line number. Refer to the original issue if you want more information.

Looking at the Onefinity post I see a small block of code starting at line 611 that makes the tool command a comment if it's the first section. It looks like this:

    if (!isFirstSection()) {
      writeBlock("T" + toolFormat.format(tool.number), conditional(getProperty("useM06"), mFormat.format(6)));
    } else {
      writeComment("T" + toolFormat.format(tool.number));
    }
Just delete all lines of this block except the second one, leaving:

    writeBlock("T" + toolFormat.format(tool.number), conditional(getProperty("useM06"), mFormat.format(6)));

**Closed by TimPaterson** 2022-10-09 16:29 UTC
